const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
try{for(const domain of ['warehouse','pong','kitchen']){
const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto((process.env.STUDY_SMOKE_URL||'http://127.0.0.1:9155')+'/try/'+domain);
await page.locator('button').filter({hasText:'Try '+(domain==='pong'?'Pong':domain==='kitchen'?'Kitchen':'Warehouse')}).click();
await page.waitForFunction(()=>typeof view!=='undefined'&&view?.state&&!busy);
await page.evaluate(async()=>{while(!questionGuide()&&!view.state.terminal)await command('action',{run_id:view.run_id,turn:view.state.turn,action:'wait'})});
const turn=await page.evaluate(()=>view.state.turn);
assert((await page.locator('#chatPanel').innerText()).includes('1/4'));
assert(await page.locator('[data-action="wait"]').isDisabled());
assert(await page.locator('[name=guideQuestion]').first().isDisabled());
assert.equal(await page.locator('[data-skip-prompts]').count(),0);
await page.locator('#aiQuestionButton').click();await page.waitForFunction(()=>questionGuide()?.guide_opened&&!busy);
assert((await page.locator('#chatPanel').innerText()).includes('2/4'));
assert(await page.locator('#sendGuideQuestion').isDisabled());
await page.locator('[name=guideQuestion][value="next"]').check();
assert((await page.locator('#chatPanel').innerText()).includes('3/4'));
assert.equal(await page.locator('#guidedAnswer').count(),0);
await page.locator('#sendGuideQuestion').click();await page.waitForFunction(()=>questionGuide()?.requested&&!busy);
assert((await page.locator('#chatPanel').innerText()).includes('4/4'));
assert((await page.locator('#guidedAnswer').innerText()).includes('next'));
assert(await page.locator('[data-action="wait"]').isDisabled());
await page.reload();await page.waitForFunction(()=>typeof view!=='undefined'&&questionGuide()?.requested&&!busy);
assert((await page.locator('#chatPanel').innerText()).includes('4/4'));
await page.locator('#studyCanvas').focus();await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>view.state.turn),turn);
await page.screenshot({path:'output/four-step-guide/'+domain+'.png',fullPage:true});
await page.locator('#confirmExplanationButton').click();await page.waitForFunction(()=>!questionGuide()&&!busy);
assert(await page.locator('[data-action="wait"]').isEnabled());
await page.locator('[data-action="wait"]').click();await page.waitForFunction(t=>view.state.turn===t+1&&!busy,turn);
await page.evaluate(async()=>{while(!pendingAutomatic()&&!pendingUnderstanding()&&!view.state.terminal)await command('action',{run_id:view.run_id,turn:view.state.turn,action:'wait'})});
if(await page.evaluate(()=>!!pendingAutomatic()&&!pendingUnderstanding()))assert(await page.locator('[data-action="wait"]').isEnabled());
assert.deepEqual(errors,[]);console.log(domain+': four-step guide, refresh, confirmation gate, and later continuation passed');await page.close();
}}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
